### ISSUE TITLE
ошибка запуска предложенной ТС : object has no attribute 'guid'

### ISSUE THREAD

**Issue by algotrading-py** [cia76/BackTraderTinkoff#1]
Здравствуйте! тестовый запуск предложенной стратегии заканчивается ошибкой:
28.08.2024 14:43:42 - BackTraderTinkoff.LimitCancel - INFO - CONNECTED
28.08.2024 14:44:00 - TinkoffPy - DEBUG - subscriptions_marketdata_handler: Пришел бар figi: "BBG004730N88"
..
Traceback (most recent call last):
  File "f:\BT\LimitCancel.py", line 150, in <module>
    cerebro.run()  # Запуск торговой системы
    ^^^^^^^^^^^^^
  File "c:\conda_env\bt-test\Lib\site-packages\backtrader\cerebro.py", line 1132, in run
    runstrat = self.runstrategies(iterstrat)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\conda_env\bt-test\Lib\site-packages\backtrader\cerebro.py", line 1303, in runstrategies
    self._runnext(runstrats)
  File "c:\conda_env\bt-test\Lib\site-packages\backtrader\cerebro.py", line 1547, in _runnext
    drets.append(d.next(ticks=False))
                 ^^^^^^^^^^^^^^^^^^^
  File "c:\conda_env\bt-test\Lib\site-packages\backtrader\feed.py", line 407, in next
    ret = self.load()
          ^^^^^^^^^^^
  File "c:\conda_env\bt-test\Lib\site-packages\backtrader\feed.py", line 480, in load
    _loadret = self._load()
               ^^^^^^^^^^^^
  File "f:\BT\BackTraderTinkoff\TKData.py", line 96, in _load
    new_bars = [new_bar for new_bar in self.store.new_bars if new_bar['guid'] == self.guid]  # Смотрим в хранилище новых бар бары с guid подписки
                                                                                 ^^^^^^^^^
  File "c:\conda_env\bt-test\Lib\site-packages\backtrader\lineseries.py", line 461, in __getattr__
    return getattr(self.lines, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Lines_LineSeries_DataSeries_OHLC_OHLCDateTime_AbstractDataBase_TKData' object has no attribute 'guid'

**Comment by cia76** [comment]
Добрый день! В текущей версии TinkoffPy такой ошибки нет. Была ранее до ввода понятия guid подписки.
